sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
    dialect: mysql
  alioss:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: LTAI5t6Nhfc6sWU7uxBYdkjH
      access-key-secret: crM7iWmf44xcYTZBPRbADAMvOnX37y
      bucket-name: mark0leadnews
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    login-ttl: 20000000000000
  wechat:
    appid: wx727e2494136f6bcf
    secret: 2211f19c74d4e2b5b0307ea7f8402912
    mchid: 1669265021
    mchSerialNo: 166926502101
    privateKeyFilePath: D:\workspace\sky-take-out\src\main\resources\apiclient_key.pem
    apiV3Key: 166926502101
    weChatPayCertFilePath: D:\workspace\sky-take-out\src\main\resources\apiclient_cert.pem
    notifyUrl: URL_ADDRESS
    refundNotifyUrl: URL_ADDRESS/refund

  jwt:
    admin-secret-key: Mark0
    admin-ttl: 7200000000000
    admin-token-name: token
    user-secret-key: Mark0
    user-ttl: 7200000000000
    user-token-name: token